name: face_recognition_app
description: Reconocimiento facial con Edge AI

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Cámara y permisos
  camera: ^0.11.0
  permission_handler: ^11.0.1
  
  # ML y procesamiento de imágenes
  tflite_flutter: ^0.11.0
  google_mlkit_face_detection: ^0.11.0
  image: ^4.1.3
  
  # UI y utilidades
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  
  # Matemáticas
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/
